"""initial database setup

Revision ID: 8af1e70d0a0f
Revises:
Create Date: 2025-03-05 17:54:05.892123

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8af1e70d0a0f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
